version: '3.3'
services:
    bctk_fe:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bctk_fe_container
        ports:
            - '80:80'
        restart: always
