version: '3.3'
services:
    hrm_fe:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: hrm_fe_container
        ports:
            - '80:80'
        restart: always
